---
title: "Viz part 2"
author: "Chen Liang"
date: "2023-10-03"
output: html_document
---
```{r}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

This results in a dataframe with 'r nrow(weather_df)'

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax,color=name)) + 
  geom_point(alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15ºC", "0", "15"),
    limits = c(-20, 30)) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right")
```
  

```{r}
ggp_temp_plot = 
weather_df |>
  ggplot(aes(x = tmin, y = tmax,color=name)) + 
  geom_point(alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package") + 
  scale_color_hue(h = c(100, 300))
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    color = "Location",
    caption = "Data from the rnoaa package") + 
  viridis::scale_color_viridis(discrete = TRUE)+
  theme(legend.position="bottom")+
  theme_bw()
```

## data argument
```{r}
weather_df |>
  ggplot(aes(x=date,y=tmax,color=name))+
  geom_point()+
  geom_smooth()

central_park_df = 
  weather_df |> 
  filter(name == "CentralPark_NY")

molokai_df = 
  weather_df |> 
  filter(name == "Molokai_HI")

ggplot(data = molokai_df, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = central_park_df) 
```


## patchwork

```{r}
weather_df |>
  ggplot(aes(x=date,y=tmax,color=name))+
  geom_point()+
  facet_grid(.~name)

ggp_temp_scatter=
  weather_df |>
  ggplot(aes(x=date,y=tmax,color=name))+
  geom_point(alpha=.5)+
  theme(legend.position = "none")

ggp_prcp_density=
  weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5) +
  theme(legend.position = "none")

ggp_tmax_date=
  weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(ggp_temp_scatter + ggp_prcp_density) / ggp_tmax_date
```

##data manipulation

```{r}
weather_df |>
  mutate(
    name=fct_relevel(name,c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |>
  ggplot(aes(x = name, y = tmax))+
  geom_boxplot()

weather_df |>
  mutate(
    name=fct_reorder(name,tmax)) |>
  ggplot(aes(x = name, y = tmax,fill=name)) + 
  geom_violin()
```

##complicate FAS plot
```{r}
litter_data = 
  read_csv("data_import_examples/FAS_litters.csv")  |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3)

pup_data = 
  read_csv("data_import_examples/FAS_pups.csv") |>
  janitor::clean_names() |>
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female"))

fas_data=
  left_join(pup_data, litter_data, by = "litter_number")

fas_data |> 
  select(sex, dose, day_of_tx, pd_ears:pd_walk) |> 
  pivot_longer(pd_ears:pd_walk,
  names_to = "outcome", 
  values_to = "pn_day")  |>
  drop_na() |> 
  mutate(outcome = forcats::fct_reorder(outcome, pn_day, median)) |> 
  ggplot(aes(x = dose, y = pn_day))+
  geom_violin()+
  facet_grid(day_of_tx ~ outcome)
```
